Develop
Helder-dlt162/Dlt pull request #3
Opened 2024-11-02 03:08 UTC by Helder-dlt162

2024-11-04 21:28 UTC, sosnoski commented on .gitignore
por que este arquivo foi removido? ele é muito importante para evitar poluição do repo. reintroduza-o, por favor

2024-11-04 21:33 UTC, sosnoski commented on app/database.py
embora pareça funcional e esteja visualmente agradavel e legivel, vou recusar pois a função destacada pode ter um design melhor

2024-11-04 21:49 UTC, sosnoski commented on app/database.py
> +    ''')
nao deveria comitar e fechar a conn?

2024-11-04 21:49 UTC, sosnoski commented on app/database.py
> +    db_cursor.execute('''
aproximação foi ruim. voce pode fazer melhor

2024-11-04 21:50 UTC, Helder-dlt162 commented on README.md
> +Coleta e salva - a cada 10 minutos, de segunda a sexta, das 7h as 17h - em xlsx as noticias mais recentes dos sites: **ANATEL, ANVISA, ANTT e ANP**.
salva em .db

2024-11-04 21:51 UTC, Helder-dlt162 commented on app/database.py
> +    ''')
ele o faz.

2024-11-04 21:51 UTC, sosnoski commented on app/main.py
> -output_filename = 'output/noticias.xlsx'
as duas var acima sao estaticas o bastante para ficarem num config.py ou .env, ou melhor ainda, ambos

2024-11-04 21:51 UTC, Helder-dlt162 commented on app/database.py
> +    db_cursor.execute('''
não compreendi

2024-11-04 21:52 UTC, sosnoski commented on app/main.py
> +output_filename = 'noticias.db'
as duas var acima sao estaticas o bastante para ficarem num config.py ou .env, ou melhor ainda, ambos

2024-11-04 21:53 UTC, sosnoski commented on README.md
> +Coleta e salva - a cada 10 minutos, de segunda a sexta, das 7h as 17h - em .db as noticias mais recentes dos sites: **ANATEL, ANVISA, ANTT e ANP**.
"em **sqlite**" mas nao perdeu ponto

2024-11-04 21:57 UTC, sosnoski commented on app/database.py
> +    db_cursor.execute('''
vc salva e deleta. sao duas operações de mutação no db. melhor seria se voce SELECT os dados¹ e comparasse programaticamente, para entao salvar

1-considere a performance quando o db crescer. pense em filtrar por data, talvez?

2024-11-04 21:58 UTC, Helder-dlt162 commented on app/database.py
> +    ''')
foi refurmulado pra commitar e fechar nas duas funções

2024-11-04 22:23 UTC, Helder-dlt162 commented on app/main.py
> +output_filename = 'noticias.db'
feito

2024-11-04 22:23 UTC, Helder-dlt162 commented on README.md
> +Coleta e salva - a cada 10 minutos, de segunda a sexta, das 7h as 17h - em .db as noticias mais recentes dos sites: **ANATEL, ANVISA, ANTT e ANP**.
alterado

2024-11-04 23:42 UTC, sosnoski requested changes
favor revisar anotacoes e submeter novamente apenas quando estiver conckuido o refactor

2024-11-04 23:42 UTC, sosnoski commented on gitignore.txt
gitignore.TXT?????????????????

WTF

.gitignore

2024-11-04 23:42 UTC, sosnoski commented on app/main.py
> +        main()
aqui voce chama main toda vez q da o time. semanticamente seria melhor se a main fosse a raiz e chamasse demais funcs. alguma coisa chamar a main soa estranho..

alem disso, aqui vc acaba chamando diversas vezes a fun create db, o que eh um processo desnecessario. melhor seria chamar uma vez e depois entrar em loop

por fim, pense em envolver processos criticos em blocos TRY-EXCEPT, com tratamento adequado de erros

2024-11-04 23:42 UTC, sosnoski commented on app/config.py
errado. nao precisa de uma func. so declara as var e chama onde precisar

2024-11-07 02:47 UTC, sosnoski commented on app/config.py
> +import this
??

2024-11-07 02:49 UTC, Helder-dlt162 commented on app/config.py
> +import this
ah, deixei teste na commit, sorry

2024-11-07 02:55 UTC, sosnoski commented on app/database.py
esta bom, mas poderia ficar menor assim:

``` new_records = [
            (item['Fonte'], item['Data'], item['Titulo'], item['Descrição'], item['Tags'], item['Link'])
            for item in news_items
            if item['Link'] not in existing_links
        ]```

2024-11-07 02:57 UTC, sosnoski commented on app/main.py
> +from config import SCRAPPING_URLS_DICT, output_filename
VAR estaticas devem ser CAPS. vc fez uma CAPS e outra nao :/

2024-11-07 02:58 UTC, sosnoski commented on app/config.py
> +output_filename = 'noticias.db'
CAPS*

2024-11-07 03:02 UTC, sosnoski commented on app/main.py
vc alterou os nomes, apenas.

o code se recupera de erros? se algum dos links retornar code 404, ou 502, 503, etc, o que acontece?

e se, por outro, mesmo q retorne code 200, retornar dados em formatos diferentes do esperado, o que acontece?

2024-11-07 03:02 UTC, sosnoski commented on app/main.py
> +def input_database():
input_database significa o que? nao me parece um bom nome pra essa funcao. nao deixa claro o que ela faz.

2024-11-07 03:03 UTC, sosnoski commented on app/main.py
>      create_database(output_filename)
voce continua tentando recriar o db toda vez que essa funçao eh adicionada. isso ja foi mencionado em review anterior, por que estou vendo isso de novo?

2024-11-07 03:06 UTC, sosnoski requested changes
de maneira geral, seu code parece inseguro. nao vi nenhum bloco try/except, embora tenha sugerido isso em review anterior.
alem disso, uma observacao sobre multiplos chamados da func q cria db enviada em review anterior foi ignorada.

mais uma vez, favor submeter apos revisar TODOS os pontos

2024-11-07 05:46 UTC, Helder-dlt162 commented on app/main.py
> +def input_database():
input = inserir
databse = base de dados
input_database = inserir na base de dados

2024-11-07 06:28 UTC, sosnoski approved these changes

2024-11-07 06:29 UTC, merged

2024-11-07 10:17 UTC, sosnoski commented on app/main.py
> +def input_database():
Amigo, *insert* significa inserir

Input *nao* significa inserir

Alem disso, a função nao insere nada na base de dados, outra função eh que faz isso. Essa aí apenas scrapa os sites e envia o dict, não é?

É um nome ruim por isso . Procure dar nomes significativos para vars, classes e funções; use ferramentas de tradução se tiver duvidas com inglês